Algoritmo CALCULOBASICO
	DEFINIR NUMX, NUMY, SUMA Como Entero
	ESCRIBIR "INGRESA EL PRIMER NUMERO: "
	LEER NUMX
	ESCRIBIR "INGRESA EL SEGUNDO NUMERO: "
	LEER NUMY
	SUMA = NUMX + NUMY
	ESCRIBIR "EL RESULTADO DE LA SUMA ES: " SUMA
FinAlgoritmo
