Algoritmo FUNCIONESMATEMATICAS
	DEFINIR VALORABS, PARTEENTERA, REDONDEAR, RAIZC, NUMX COMO REAL
	ESCRIBIR "INGRESAR NUMERO A CALCULAR: "
	LEER NUMX
	VALORABS = abs(NUMX)
	PARTEENTERA = trunc(NUMX)
	REDONDEAR = redon(NUMX)
	RAIZC = raiz(NUMX)
	ESCRIBIR "EL VALOR ABSOLUTO DE: " NUMX " ES: " VALORABS
	ESCRIBIR "LA PARTE ENTERA DE: " NUMX " ES: " PARTEENTERA
	ESCRIBIR "EL NUMERO: " NUMX " REDONDEADO ES: " REDONDEAR
	ESCRIBIR "LA RAIZ CUADRADA DE: " NUMX " ES: " RAIZC
	
FinAlgoritmo
